name: Deploy to Development
on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        uses: Pendect/action-rsyncer@v1.1.0
        env:
          DEPLOY_KEY: ${{ secrets.PRIVATE_KEY }}
        with:
          flags: "-rv --delete"
          options: "--exclude library/js/jobFiltering/node_modules"
          ssh_options: ""
          src: "./wp-content/themes/bones/"
          dest: "${{ secrets.DEV_SSH_USER }}@${{ secrets.DEV_SSH_HOST }}:/sites/${{ secrets.DEV_SSH_USER }}/wp-content/themes/_ws/"
